pipeline {
    agent any
     tools {
        maven 'Maven 4.3.9'
        jdk 'jdk9'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
       stage('Complete') {
            steps {
                echo 'Completed Test- working' 
            }    
        }
    }
}
}
